repo_name: facebook/s2t-large-librispeech-asr
sampling_rate: 16000  # sampling rate the network was trained on
use_pca: False
pca_comps: 50
layers:

- layer_name: model.encoder.conv.conv_layers.0
  layer_id: 0
  layer_type: conv
  RF: 60   # RF is in ms.

- layer_name: model.encoder.conv.conv_layers.1
  layer_id: 1
  layer_type: conv
  RF: 140   # RF is in ms.

- layer_name: model.encoder.layers.0.final_layer_norm
  layer_id: 2
  layer_type: transformer
  RF: 0   # RF is irrelevant for transformer layer
- layer_name: model.encoder.layers.1.final_layer_norm
  layer_id: 3
  layer_type: transformer
  RF: 0   # RF is irrelevant for transformer layer
- layer_name: model.encoder.layers.2.final_layer_norm
  layer_id: 4
  layer_type: transformer
  RF: 0   # RF is irrelevant for transformer layer
- layer_name: model.encoder.layers.3.final_layer_norm
  layer_id: 5
  layer_type: transformer
  RF: 0   # RF is irrelevant for transformer layer
- layer_name: model.encoder.layers.4.final_layer_norm
  layer_id: 6
  layer_type: transformer
  RF: 0   # RF is irrelevant for transformer layer
- layer_name: model.encoder.layers.5.final_layer_norm
  layer_id: 7
  layer_type: transformer
  RF: 0   # RF is irrelevant for transformer layer
- layer_name: model.encoder.layers.6.final_layer_norm
  layer_id: 8
  layer_type: transformer
  RF: 0   # RF is irrelevant for transformer layer
- layer_name: model.encoder.layers.7.final_layer_norm
  layer_id: 9
  layer_type: transformer
  RF: 0   # RF is irrelevant for transformer layer
- layer_name: model.encoder.layers.8.final_layer_norm
  layer_id: 10
  layer_type: transformer
  RF: 0   # RF is irrelevant for transformer layer
- layer_name: model.encoder.layers.9.final_layer_norm
  layer_id: 11
  layer_type: transformer
  RF: 0   # RF is irrelevant for transformer layer
- layer_name: model.encoder.layers.10.final_layer_norm
  layer_id: 12
  layer_type: transformer
  RF: 0   # RF is irrelevant for transformer layer
- layer_name: model.encoder.layers.11.final_layer_norm
  layer_id: 13
  layer_type: transformer
  RF: 0   # RF is irrelevant for transformer layer

