pretrained: False
# shuffle_weights: False

use_pca: False
layers:
- layer_name: conv1.activation 
  layer_id: 0
  RF: 1.94               #(1.94 ms)
  layer_type: conv
- layer_name: conv2.activation
  layer_id: 1
  RF: 4.44               #(4.44 ms)
  layer_type: conv
- layer_name: conv3.activation
  layer_id: 2
  RF: 9.44               #(9.44 ms)
  layer_type: conv
- layer_name: conv4.activation
  layer_id: 3
  RF: 19.44               #(19.44 ms)
  layer_type: conv
- layer_name: conv5.activation
  layer_id: 4
  RF: 40               #(39.44 ms)
  layer_type: conv
- layer_name: conv6.activation
  layer_id: 5
  RF: 80               #(79.44 ms)
  layer_type: conv
- layer_name: conv7.activation
  layer_id: 6 # 
  RF: 120 #120 #80 #40 #20 # 120               #(119.44 ms) 20 #40 #80 #120 #160
  layer_type: conv
- layer_name: conv8.activation
  layer_id: 7
  RF: 160               #(159.44 ms)
  layer_type: conv

- layer_name: conv9.activation
  layer_id: 8
  RF: 280               #(279.44 ms)
  layer_type: conv
- layer_name: conv10.activation
  layer_id: 9
  RF: 400               #(399.44 ms)
  layer_type: conv

- layer_name: conv11.activation
  layer_id: 10
  RF: 520               #(519.44 ms)
  layer_type: conv
- layer_name: conv12.activation
  layer_id: 11
  RF: 640               #(639.44 ms)
  layer_type: conv
  
- layer_name: conv13.activation
  layer_id: 12
  RF: 1240               #(1239.44 ms)
  layer_type: conv
- layer_name: conv14.activation
  layer_id: 13
  RF: 1240
  layer_type: conv
# - layer_name: conv15
#   layer_id: 14
#   layer_type: conv
